apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
    - command:
      - kube-scheduler
      - --authentication-kubeconfig=/etc/kuberenetes/scheduler.conf
      - --authorization-kubeconfig=/etc/kuberenetes/scheduler.conf
      - --bind-address=127.0.0.1
      - --kubeconfig=/etc/kubernetes/scheduler.conf
      - --leader-elect=false
      - --port=0
      - --config=/etc/kubernetes/kube-scheduler-config.yaml
      image: k8s.gcr.io/kube-scheduler:v1.19.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 15
      name: kube-scheduler
      resources:
        requests:
          cpu: 100m
      startupProbe:
        failureThreshold: 24
        httpGet:
          host: 127.0.0.1
          path: /heaalthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 15
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/kubernetes/kube-scheduler-config.yaml
          name: kube-scheduler-config
          readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
    - name: kube-scheduler-config
      hostPath:
        path: /etc/kuberentes/kube-scheduler-config.yaml
        type: FileOrCreate
      
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler-extender
    tier: control-plane
  name: kube-scheduler-extender
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - image: poorlydefinedbehaviour/k8s-scheduler-extender:v1
      name: kube-scheduler-exetender
---
# Is static
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
extends:
  - urlPrefix: http://localhost:8888
    filterVerb: filter
    prioritizeVerb: prioritize
    weight: 1