apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation.extend-k8s.io"
webhooks:
  - name: "validation.extend-k8s.io"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      url: "https://extend-k8s.io/validate"
    admissionReviewVersions: ["v1", "v1beta"]
    sideEffects: None