apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutation.extend-k8s.io"
webhooks:
  - name: "mutation.extend-k8s.io"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["secrets"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "extension"
        name: "mutation-service"
      caBundle: "Ci0tLS0tQk...tLS0K"
    adimissionReviewVersions: ["v1", "v1beta"]
    sideEffects: None