apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: timeseriesdbs.extend-k8s.io
spec:
  group: extend-k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbType:
                  type: string
                replicas:
                  type: integer
                status:
                  type: object
                  properties:
                    stage:
                      type: string
                    message:
                      type: string
  scope: Namespaced
  names:
    plural: timeseriesdbs
    singular: timeseriesdb
    kind: TimeseriesDB
    shortNames:
      - tsdb
---
apiVersion: extend-k8s.io/v1
kind: TimeseriesDB
metadata:
  name: exmaple-tsdb
spec:
  dbType: InfluxDB
  replicas: 4
  status:
    stage: Created
    message: NewTimeSeriesDB